// Map tên file ảnh với require statement
export const images = {
  "buncha_hanoi.jpg": require("@/assets/public/buncha_hanoi.jpg"),
  "burger-party.jpg": require("@/assets/public/burger-party.jpg"),
  "classic-beef-burger.png": require("@/assets/public/classic-beef-burger.png"),
  "colorful-fruit-smoothie.png": require("@/assets/public/colorful-fruit-smoothie.png"),
  "com-tam-suon-bi-cha.jpg": require("@/assets/public/com-tam-suon-bi-cha.jpg"),
  "combo-meal-small.jpg": require("@/assets/public/combo-meal-small.jpg"),
  "combo-meal.png": require("@/assets/public/combo-meal.png"),
  "comga_xoimo.jpg": require("@/assets/public/comga_xoimo.jpg"),
  "cozy-coffee-cafe.png": require("@/assets/public/cozy-coffee-cafe.png"),
  "cozy-corner-cafe.png": require("@/assets/public/cozy-corner-cafe.png"),
  "creamy-chicken-salad.png": require("@/assets/public/creamy-chicken-salad.png"),
  "crispy-fried-chicken.png": require("@/assets/public/crispy-fried-chicken.png"),
  "cutlery-fork-knife.jpg": require("@/assets/public/cutlery-fork-knife.jpg"),
  "diverse-food-spread.png": require("@/assets/public/diverse-food-spread.png"),
  "fried-potatoes.jpg": require("@/assets/public/fried-potatoes.jpg"),
  "milk-drink.jpg": require("@/assets/public/milk-drink.jpg"),
  "pizza-party.jpg": require("@/assets/public/pizza-party.jpg"),
  "pizza-xuc-xich-pho-mai-vuong.jpg": require("@/assets/public/pizza-xuc-xich-pho-mai-vuong.jpg"),
  "placeholder.jpg": require("@/assets/public/placeholder.jpg"),
  "restaurant-food-variety.png": require("@/assets/public/restaurant-food-variety.png"),
  "seafood-restaurant.png": require("@/assets/public/seafood-restaurant.png"),
  "simple-rice-bowl.png": require("@/assets/public/simple-rice-bowl.png"),
  "spicy-chicken.jpg": require("@/assets/public/spicy-chicken.jpg"),
  "sushi-party.jpg": require("@/assets/public/sushi-party.jpg"),
  "trasuamatcha_master.png": require("@/assets/public/trasuamatcha_master.png"),
  "vibrant-green-salad.png": require("@/assets/public/vibrant-green-salad.png"),
  "vibrant-salad-bowl.png": require("@/assets/public/vibrant-salad-bowl.png"),
} as const;
